### ISSUE TITLE
enc not working in sjmisc::read_spss

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjmisc#62]
I could not specify the encoding of data via this argument. I like this argument to function like the argument "reencode" in foreign::read.spss. 
Thanks!

**Comment by sjPlot** [comment]
Encoding should be managed by *haven*'s `read_spss()`-function. I think, default is UTF-8?

**Comment by frankcsliu** [comment]
yes, but "enc" continues to appear in the manual when I typed ?read_spss. I thought it will work without switching to haven.

**Comment by strengejacke** [comment]
No, you don't need to switch to haven, `sjlabelled::read_spss()` simply wraps `haven::read_spss()` and additionally handles tagged NA values in a slightly different way. So, the core feature of importing data and handling the encoding is in _haven_. I know Hadley has fixed some encoding issues some time ago (see https://github.com/tidyverse/haven/commit/2e0d68ce333c8d6bae119073a0abd79098d18f2d), that's why I removed the `enc`-argument.
