### ISSUE TITLE
frq() always prints

### ISSUE THREAD

**Issue by grishin1** [strengejacke/sjmisc#66]
`frq` prints even when assigning its output to a variable.
Please consider:
``` r
sjmisc::frq(mtcars, cyl)
#>   val frq label raw.prc valid.prc cum.prc
#>     4  11     4   34.38     34.38   34.38
#>     6   7     6   21.88     21.88   56.25
#>     8  14     8   43.75     43.75  100.00
#>  <NA>   0    NA    0.00        NA      NA
```
still prints:
``` r
x <- sjmisc::frq(mtcars, cyl)
#>   val frq label raw.prc valid.prc cum.prc
#>     4  11     4   34.38     34.38   34.38
#>     6   7     6   21.88     21.88   56.25
#>     8  14     8   43.75     43.75  100.00
#>  <NA>   0    NA    0.00        NA      NA
```
Compare to xtabs:
``` r
y <- xtabs(~cyl, mtcars)
```
evaluating output saved in `y`
``` r
y
#> cyl
#>  4  6  8 
#> 11  7 14
```
The problem is in the calls to `print` which defeats the purpose of invisible return in the end of the function.
The fact that `frq` tries to return its result invisibly suggests that printing 'no matter what' was not a desired effect. Please confirm.

**Comment by strengejacke** [comment]
At the moment, always printing is a desired result. This is because the output, especially for grouped data frames, contains additional information (variable labels, grouping labels) that is not captured in the output.

I could re-write the function, add these information as attributes and write a print-method, so printing is not done when someone just wants to capture the results.
