### ISSUE TITLE
regarding the order of the reference in ref_lvl() results

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjmisc#88]
after re-leveling the variable, the val of the variables were not changed accordingly. 
[please click here to see the R script and dataset for replicating the issue](https://drive.google.com/drive/folders/1Lc_aJ42zZHkYmhYNLFsJId7KZt_ME-aA?usp=sharing)

**Comment by frankcsliu** [comment]
sorry for the missing codes. I have just updated the R script.

**Comment by strengejacke** [comment]
I just downloaded the script and the data file, still the `turnout` variable is missing.

**Comment by frankcsliu** [comment]
I checked the codes and the data set again and uploaded them again.

The missed variables are ensured in both R script and the rda file.

Thanks.

**Comment by strengejacke** [comment]
Ok, I checked your example, and the function works as intended. `ref_lvl()` recodes the factors, so that the new reference level will get the value `1`, while all other values are recoded, if necessary. In your example, `KMT` was the label for value 2, and `DPP` the label for value 1. After `ref_lvl()`, the variable `pID` was recoded, value 1 into 2 and value 2 into 1, and `KMT` was now the label for value 1, and `DPP` the label for value 2 accordingly.

**Comment by frankcsliu** [comment]
Could you give the following need a second thought? Intuitively we social scientists like to change base to evaluate and better interpret regression results. If we cannot hold link between value and label, it is hard to read the printed result. Hopefully there is a way to keep the value-label connection. That is, when I change the base, the labels change accordingly. This will make this function really helpful. Thanks.

**Comment by strengejacke** [comment]
This is already happening when you use `ref_lvl()`, see your examples with `frq(kao06$pID)` before and after using `ref_lvl()`.

`ref_lvl()` _recodes_ the vector, that's why the former 2nd level becomes the first level. Hence, in the summary output, you still see `pID2` to `pID6` - because `pID1` relfects now the former values from `pID2`. That's the intention of `ref_lvl()`, and the main difference to base `relevel()`.
